# Generated by Django 5.2.3 on 2025-06-20 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugares_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_de_gases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('ubicacion', models.CharField(choices=[('Mina Norte - Sección A', 'Mina Norte - Sección A'), ('Mina Norte - Sección B', 'Mina Norte - Sección B'), ('Mina Sur - Sección A', 'Mina Sur - Sección A'), ('Mina Este - Galería 1', 'Mina Este - Galería 1'), ('Mina Este - Galería 3', 'Mina Este - Galería 3'), ('Mina Norte - Sección D', 'Mina Norte - Sección D'), ('Mina Oeste - Galería 1', 'Mina Oeste - Galería 1'), ('Mina Oeste - Galería 2', 'Mina Oeste - Galería 2')], max_length=100)),
                ('tipo_gas', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('Normal', 'Normal'), ('Advertencia', 'Advertencia'), ('Peligro', 'Peligro')], max_length=20)),
                ('registrado_por', models.CharField(max_length=50)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_del_lugar_de_trabajo', to='lugares_trabajo.lugares_de_trabajo')),
            ],
        ),
    ]
