# Generated by Django 5.2.3 on 2025-06-20 02:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlDeIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(default=django.utils.timezone.now)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado_salud_entrada', models.CharField(blank=True, choices=[('Bien', 'Bien'), ('Regular', 'Regular'), ('Mal', 'Mal')], max_length=30, null=True)),
                ('estado_salud_Salida', models.CharField(blank=True, choices=[('Bien', 'Bien'), ('Regular', 'Regular'), ('Mal', 'Mal')], max_length=30, null=True)),
                ('lugar_trabajo', models.CharField(blank=True, choices=[('Mina Norte', 'Mina Norte'), ('Mina Sur', 'Mina Sur'), ('Procesamiento', 'Procesamiento'), ('Administración', 'Administración'), ('Mantenimiento', 'Mantenimiento')], max_length=100, null=True)),
                ('estado', models.CharField(default='activo', max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.empleado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ingreso', to='administracion.proyecto')),
            ],
        ),
    ]
