# Generated by Django 5.2.3 on 2025-06-20 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugares_de_trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=200)),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('trabajadores', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('estimated_end', models.DateField()),
                ('progreso', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.proyecto')),
            ],
        ),
    ]
